export type PasswordStateType =
  | 'PASSCODE_SIGNUP'
  | 'PASSCODE_LOGIN'
  | 'PASSCODE_RESET'
  | 'PASSCODE_CORRECT'
  | 'PASSCODE_RESET_RECONFIRM'
  | 'SIGNUP_PASSCODE_RECONFIRM'
  | 'PASSCODE_NOT_CORRECT'
  | '';
